# Generated by Django 3.1.7 on 2021-02-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, null=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='투표', max_length=500, verbose_name='제목')),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('t', 'trash')], default='p', max_length=2, verbose_name='게시글 공개 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
                ('options', models.ManyToManyField(to='poll.Option', verbose_name='항목')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poll.option', verbose_name='선택한 항목')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poll.poll', verbose_name='참가한 투표')),
            ],
        ),
    ]
